### ISSUE TITLE
license

### ISSUE THREAD

**Issue by a-n-d-a-i** [Caedo/raylib_wasm_odin#1]
From my understanding, if no license is specified, then the default is for the code to be copyrighted, and all rights reserved.
I am guessing this was not intentional, so I would suggest adding a license to the readme and/or repo.

On a related note, I used this repo as the basis for an online game I'm developing https://github.com/avelican/boxfight
Thanks a lot, wouldn't have been possible without your work :)

**Comment by Caedo** [comment]
Hello, I'm glad that my experiments are useful to you :D
Just added licence file, it's just Public Domain.

Also it's worth noting, that the idea of using small emscriptem program as a host for odin code is not entirely mine, but was shared to me by ncharlie on Odin Discord. I just simplified it a little (he was also using zig-cc), experimented with "what can I do" and documented my findings :>
